import { Job } from "@/types/job";

export const demoJobs: Job[] = [
  // Software Development
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$140k - $180k",
    description:
      "We are looking for an experienced Frontend Developer to join our dynamic team...",
    requirements: [
      "5+ years React experience",
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
    ],
    responsibilities: [
      "Build responsive web apps",
      "Mentor junior developers",
      "Code reviews",
    ],
    postedDate: "2024-01-15",
    logo: "TC",
    category: "Engineering",
    experienceLevel: "Senior",
    skills: ["React", "TypeScript", "Next.js", "Tailwind"],
    benefits: ["Health insurance", "401k", "Remote work", "Stock options"],
    applyCount: 45,
    remote: true,
  },
  {
    id: "2",
    title: "Full Stack Engineer",
    company: "StartupHub",
    location: "Remote",
    type: "Remote",
    salary: "$120k - $160k",
    description:
      "Join our fast-growing startup building innovative solutions...",
    requirements: ["3+ years full stack", "Node.js", "React", "PostgreSQL"],
    responsibilities: [
      "Develop features",
      "API design",
      "Database optimization",
    ],
    postedDate: "2024-01-10",
    logo: "SH",
    category: "Engineering",
    experienceLevel: "Mid",
    skills: ["Node.js", "React", "PostgreSQL", "AWS"],
    benefits: ["Unlimited PTO", "Remote stipend", "Equity"],
    applyCount: 89,
    remote: true,
  },
  {
    id: "3",
    title: "Backend Developer",
    company: "DataSystems",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$130k - $170k",
    description: "Build scalable backend systems for enterprise clients...",
    requirements: ["Python", "Django", "Microservices", "Docker"],
    responsibilities: [
      "API development",
      "System architecture",
      "Performance tuning",
    ],
    postedDate: "2024-01-12",
    logo: "DS",
    category: "Engineering",
    experienceLevel: "Senior",
    skills: ["Python", "Django", "Docker", "Kubernetes"],
    benefits: ["Competitive salary", "Remote options", "Learning budget"],
    applyCount: 34,
    remote: true,
  },
  {
    id: "4",
    title: "Mobile Developer (iOS)",
    company: "AppWorks",
    location: "New York, NY",
    type: "Full-time",
    salary: "$135k - $175k",
    description: "Create amazing iOS experiences for millions of users...",
    requirements: ["Swift", "iOS SDK", "UIKit/SwiftUI", "Combine"],
    responsibilities: [
      "Build iOS apps",
      "App Store submission",
      "Performance optimization",
    ],
    postedDate: "2024-01-08",
    logo: "AW",
    category: "Mobile",
    experienceLevel: "Mid",
    skills: ["Swift", "SwiftUI", "CoreData", "Firebase"],
    benefits: ["Health/dental", "Gym membership", "Stock options"],
    applyCount: 23,
    remote: false,
  },
  {
    id: "5",
    title: "Android Developer",
    company: "MobileFirst",
    location: "Seattle, WA",
    type: "Full-time",
    salary: "$125k - $165k",
    description: "Develop cutting-edge Android applications...",
    requirements: ["Kotlin", "Android SDK", "Jetpack Compose", "MVVM"],
    responsibilities: [
      "Android development",
      "Play Store deployment",
      "Code quality",
    ],
    postedDate: "2024-01-14",
    logo: "MF",
    category: "Mobile",
    experienceLevel: "Mid",
    skills: ["Kotlin", "Jetpack Compose", "Room", "Retrofit"],
    benefits: ["401k matching", "Flexible hours", "Remote friendly"],
    applyCount: 41,
    remote: true,
  },

  // Data & AI
  {
    id: "6",
    title: "Data Scientist",
    company: "AI Innovations",
    location: "Boston, MA",
    type: "Full-time",
    salary: "$150k - $200k",
    description: "Use machine learning to solve complex business problems...",
    requirements: ["Python", "TensorFlow/PyTorch", "SQL", "Statistics"],
    responsibilities: ["Build ML models", "Data analysis", "A/B testing"],
    postedDate: "2024-01-09",
    logo: "AI",
    category: "Data",
    experienceLevel: "Senior",
    skills: ["Python", "TensorFlow", "SQL", "Pandas"],
    benefits: ["Research budget", "Conference attendance", "Flexible schedule"],
    applyCount: 67,
    remote: true,
  },
  {
    id: "7",
    title: "Machine Learning Engineer",
    company: "DeepLearning AI",
    location: "Palo Alto, CA",
    type: "Full-time",
    salary: "$160k - $210k",
    description: "Deploy ML models at scale...",
    requirements: ["MLOps", "Python", "AWS/GCP", "Kubernetes"],
    responsibilities: ["Model deployment", "Pipeline automation", "Monitoring"],
    postedDate: "2024-01-11",
    logo: "DL",
    category: "AI/ML",
    experienceLevel: "Senior",
    skills: ["Python", "MLflow", "AWS SageMaker", "Docker"],
    benefits: ["Equity", "Premium healthcare", "Unlimited PTO"],
    applyCount: 52,
    remote: true,
  },
  {
    id: "8",
    title: "Data Engineer",
    company: "DataStream",
    location: "Chicago, IL",
    type: "Full-time",
    salary: "$130k - $170k",
    description: "Build and maintain data pipelines...",
    requirements: ["SQL", "Python", "Spark", "Airflow"],
    responsibilities: ["ETL pipelines", "Data warehousing", "Data quality"],
    postedDate: "2024-01-13",
    logo: "DS",
    category: "Data",
    experienceLevel: "Mid",
    skills: ["SQL", "Python", "Spark", "Airflow", "dbt"],
    benefits: ["Remote work", "Tuition reimbursement", "Bonus"],
    applyCount: 38,
    remote: true,
  },

  // DevOps & Cloud
  {
    id: "9",
    title: "DevOps Engineer",
    company: "CloudNative",
    location: "Remote",
    type: "Remote",
    salary: "$140k - $180k",
    description: "Automate infrastructure and deployment processes...",
    requirements: ["AWS", "Terraform", "Kubernetes", "CI/CD"],
    responsibilities: ["Infrastructure as Code", "Monitoring", "Security"],
    postedDate: "2024-01-07",
    logo: "CN",
    category: "DevOps",
    experienceLevel: "Senior",
    skills: ["AWS", "Terraform", "K8s", "Jenkins", "Prometheus"],
    benefits: ["Home office stipend", "Professional development", "4-day week"],
    applyCount: 73,
    remote: true,
  },
  {
    id: "10",
    title: "Site Reliability Engineer",
    company: "ScaleOps",
    location: "Denver, CO",
    type: "Full-time",
    salary: "$145k - $185k",
    description: "Ensure reliability and scalability of systems...",
    requirements: ["Linux", "Cloud platforms", "Monitoring tools", "Scripting"],
    responsibilities: ["Incident response", "Capacity planning", "Automation"],
    postedDate: "2024-01-06",
    logo: "SO",
    category: "DevOps",
    experienceLevel: "Senior",
    skills: ["Linux", "AWS", "Python", "Grafana", "PagerDuty"],
    benefits: ["On-call bonus", "Wellness stipend", "401k"],
    applyCount: 29,
    remote: true,
  },

  // Product Management
  {
    id: "11",
    title: "Product Manager",
    company: "ProductLabs",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$150k - $190k",
    description: "Lead product development from concept to launch...",
    requirements: ["3+ years PM experience", "Agile/Scrum", "Data-driven"],
    responsibilities: [
      "Roadmap planning",
      "Stakeholder management",
      "User research",
    ],
    postedDate: "2024-01-05",
    logo: "PL",
    category: "Product",
    experienceLevel: "Mid",
    skills: ["Product Strategy", "Analytics", "User Stories", "JIRA"],
    benefits: ["Stock options", "Leadership training", "Remote options"],
    applyCount: 56,
    remote: true,
  },
  {
    id: "12",
    title: "Technical Product Manager",
    company: "TechInnovate",
    location: "Seattle, WA",
    type: "Full-time",
    salary: "$160k - $200k",
    description: "Bridge technical and business teams...",
    requirements: ["Technical background", "API knowledge", "Agile expertise"],
    responsibilities: [
      "Technical requirements",
      "Architecture decisions",
      "Sprint planning",
    ],
    postedDate: "2024-01-10",
    logo: "TI",
    category: "Product",
    experienceLevel: "Senior",
    skills: ["APIs", "SDLC", "Technical Writing", "Roadmapping"],
    benefits: ["Tech budget", "Conference access", "Flexible hours"],
    applyCount: 44,
    remote: true,
  },

  // Design
  {
    id: "13",
    title: "Senior UX/UI Designer",
    company: "DesignStudio",
    location: "Los Angeles, CA",
    type: "Full-time",
    salary: "$120k - $160k",
    description: "Create beautiful and intuitive user experiences...",
    requirements: ["Figma", "User research", "Prototyping", "Design systems"],
    responsibilities: [
      "Wireframing",
      "User testing",
      "Collaboration with devs",
    ],
    postedDate: "2024-01-12",
    logo: "DS",
    category: "Design",
    experienceLevel: "Senior",
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping"],
    benefits: ["Creative budget", "Adobe subscription", "Workshops"],
    applyCount: 61,
    remote: true,
  },
  {
    id: "14",
    title: "Product Designer",
    company: "CreativeMinds",
    location: "Remote",
    type: "Remote",
    salary: "$110k - $150k",
    description: "Design beautiful products that users love...",
    requirements: [
      "UI/UX portfolio",
      "Design thinking",
      "Collaboration skills",
    ],
    responsibilities: ["Visual design", "Interaction design", "Design reviews"],
    postedDate: "2024-01-09",
    logo: "CM",
    category: "Design",
    experienceLevel: "Mid",
    skills: ["Sketch", "InVision", "HTML/CSS basics", "User flows"],
    benefits: ["Design tool stipend", "Remote first", "Creative freedom"],
    applyCount: 38,
    remote: true,
  },

  // Marketing
  {
    id: "15",
    title: "Digital Marketing Manager",
    company: "MarketPros",
    location: "New York, NY",
    type: "Full-time",
    salary: "$90k - $130k",
    description: "Lead digital marketing campaigns...",
    requirements: ["SEO/SEM", "Google Analytics", "Content strategy"],
    responsibilities: [
      "Campaign management",
      "ROI analysis",
      "Team leadership",
    ],
    postedDate: "2024-01-11",
    logo: "MP",
    category: "Marketing",
    experienceLevel: "Mid",
    skills: ["SEO", "Google Ads", "Analytics", "Email Marketing"],
    benefits: ["Marketing budget", "Performance bonus", "Remote days"],
    applyCount: 42,
    remote: false,
  },
  {
    id: "16",
    title: "Content Marketing Specialist",
    company: "ContentFirst",
    location: "Remote",
    type: "Remote",
    salary: "$70k - $95k",
    description: "Create engaging content for B2B audiences...",
    requirements: ["Writing skills", "SEO", "Content strategy"],
    responsibilities: ["Blog posts", "Case studies", "Social media"],
    postedDate: "2024-01-13",
    logo: "CF",
    category: "Marketing",
    experienceLevel: "Entry",
    skills: ["Copywriting", "WordPress", "LinkedIn", "Email marketing"],
    benefits: ["Flexible schedule", "Learning budget", "Content tools"],
    applyCount: 27,
    remote: true,
  },

  // Sales
  {
    id: "17",
    title: "Sales Development Representative",
    company: "SalesForcePro",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$60k - $80k + Commission",
    description: "Generate leads and qualify prospects...",
    requirements: ["Communication skills", "CRM experience", "Goal-oriented"],
    responsibilities: [
      "Outbound calls",
      "Lead qualification",
      "Demo scheduling",
    ],
    postedDate: "2024-01-10",
    logo: "SP",
    category: "Sales",
    experienceLevel: "Entry",
    skills: ["Salesforce", "Cold calling", "LinkedIn Sales Nav", "Negotiation"],
    benefits: ["Commission structure", "Sales training", "Career growth"],
    applyCount: 51,
    remote: true,
  },
  {
    id: "18",
    title: "Account Executive",
    company: "EnterpriseSoft",
    location: "Chicago, IL",
    type: "Full-time",
    salary: "$100k - $140k + Commission",
    description: "Close enterprise deals and manage key accounts...",
    requirements: [
      "5+ years sales",
      "Enterprise experience",
      "Solution selling",
    ],
    responsibilities: ["Deal closing", "Account management", "Forecasting"],
    postedDate: "2024-01-08",
    logo: "ES",
    category: "Sales",
    experienceLevel: "Senior",
    skills: ["Strategic selling", "Negotiation", "CRM", "Prospecting"],
    benefits: ["High commission", "Car allowance", "President club"],
    applyCount: 33,
    remote: true,
  },

  // Customer Success
  {
    id: "19",
    title: "Customer Success Manager",
    company: "ClientFirst",
    location: "Remote",
    type: "Remote",
    salary: "$80k - $110k",
    description: "Ensure customer satisfaction and retention...",
    requirements: ["Communication", "Problem-solving", "SaaS experience"],
    responsibilities: ["Onboarding", "Account health", "Upselling"],
    postedDate: "2024-01-14",
    logo: "CF",
    category: "Customer Success",
    experienceLevel: "Mid",
    skills: ["CRM", "Customer support", "Training", "Analytics"],
    benefits: ["Remote work", "Wellness program", "Stock options"],
    applyCount: 39,
    remote: true,
  },
  {
    id: "20",
    title: "Technical Support Engineer",
    company: "SupportHub",
    location: "Portland, OR",
    type: "Full-time",
    salary: "$70k - $90k",
    description: "Provide technical support to enterprise customers...",
    requirements: ["Technical background", "Troubleshooting", "Communication"],
    responsibilities: ["Ticket resolution", "Bug reporting", "Documentation"],
    postedDate: "2024-01-07",
    logo: "SH",
    category: "Support",
    experienceLevel: "Entry",
    skills: ["Linux", "APIs", "SQL", "JIRA", "Zendesk"],
    benefits: ["Shift differential", "Training", "Certification"],
    applyCount: 46,
    remote: true,
  },

  // Human Resources
  {
    id: "21",
    title: "HR Generalist",
    company: "PeopleFirst",
    location: "Dallas, TX",
    type: "Full-time",
    salary: "$65k - $85k",
    description: "Manage HR operations and employee relations...",
    requirements: ["HR experience", "Employment law", "Communication"],
    responsibilities: ["Recruitment", "Onboarding", "Benefits admin"],
    postedDate: "2024-01-12",
    logo: "PF",
    category: "HR",
    experienceLevel: "Mid",
    skills: ["HRIS", "Recruiting", "Employee relations", "Compliance"],
    benefits: ["HR certification", "Flexible hours", "401k"],
    applyCount: 28,
    remote: false,
  },
  {
    id: "22",
    title: "Technical Recruiter",
    company: "TalentFind",
    location: "Remote",
    type: "Remote",
    salary: "$80k - $120k",
    description: "Source and recruit top technical talent...",
    requirements: ["Tech recruiting", "Sourcing", "Interviewing"],
    responsibilities: ["Candidate sourcing", "Screening", "Offer negotiation"],
    postedDate: "2024-01-09",
    logo: "TF",
    category: "HR",
    experienceLevel: "Mid",
    skills: [
      "LinkedIn Recruiter",
      "Greenhouse",
      "Tech screening",
      "Negotiation",
    ],
    benefits: ["Placement bonus", "Remote work", "Unlimited PTO"],
    applyCount: 34,
    remote: true,
  },

  // Finance
  {
    id: "23",
    title: "Financial Analyst",
    company: "FinancePro",
    location: "New York, NY",
    type: "Full-time",
    salary: "$85k - $115k",
    description: "Analyze financial data and create reports...",
    requirements: ["Excel", "Financial modeling", "Analytical skills"],
    responsibilities: ["Budgeting", "Forecasting", "Variance analysis"],
    postedDate: "2024-01-11",
    logo: "FP",
    category: "Finance",
    experienceLevel: "Entry",
    skills: ["Excel", "SQL", "Tableau", "Financial modeling"],
    benefits: ["CPA support", "Bonus", "401k matching"],
    applyCount: 47,
    remote: true,
  },
  {
    id: "24",
    title: "Accounting Manager",
    company: "AccountFirst",
    location: "Chicago, IL",
    type: "Full-time",
    salary: "$100k - $140k",
    description: "Manage accounting team and financial reporting...",
    requirements: ["CPA", "GAAP", "Team management"],
    responsibilities: ["Month-end close", "Audits", "Team supervision"],
    postedDate: "2024-01-06",
    logo: "AF",
    category: "Finance",
    experienceLevel: "Senior",
    skills: ["QuickBooks", "GAAP", "Auditing", "Leadership"],
    benefits: ["CPA renewal", "Bonus", "Remote options"],
    applyCount: 31,
    remote: false,
  },

  // Operations
  {
    id: "25",
    title: "Operations Manager",
    company: "OpsPro",
    location: "Atlanta, GA",
    type: "Full-time",
    salary: "$90k - $130k",
    description: "Streamline operations and improve efficiency...",
    requirements: ["Process improvement", "Team management", "Analytics"],
    responsibilities: [
      "Process optimization",
      "KPI tracking",
      "Budget management",
    ],
    postedDate: "2024-01-10",
    logo: "OP",
    category: "Operations",
    experienceLevel: "Mid",
    skills: ["Six Sigma", "Project management", "Data analysis", "Leadership"],
    benefits: ["Performance bonus", "Health insurance", "401k"],
    applyCount: 36,
    remote: true,
  },
  {
    id: "26",
    title: "Project Coordinator",
    company: "ProjectHub",
    location: "Remote",
    type: "Remote",
    salary: "$55k - $75k",
    description: "Coordinate projects and support project managers...",
    requirements: ["Organization", "Communication", "Tools proficiency"],
    responsibilities: [
      "Schedule management",
      "Documentation",
      "Team coordination",
    ],
    postedDate: "2024-01-13",
    logo: "PH",
    category: "Operations",
    experienceLevel: "Entry",
    skills: ["Asana", "JIRA", "Excel", "Communication"],
    benefits: ["Remote work", "Learning stipend", "Flexible hours"],
    applyCount: 52,
    remote: true,
  },

  // Legal
  {
    id: "27",
    title: "Corporate Counsel",
    company: "LegalTech",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$180k - $250k",
    description: "Provide legal advice on corporate matters...",
    requirements: ["Law degree", "Bar admission", "Corporate law"],
    responsibilities: ["Contract review", "Compliance", "Risk management"],
    postedDate: "2024-01-08",
    logo: "LT",
    category: "Legal",
    experienceLevel: "Senior",
    skills: ["Contract law", "Negotiation", "Compliance", "Risk assessment"],
    benefits: ["Bar dues paid", "Bonus", "Stock options"],
    applyCount: 19,
    remote: false,
  },
  {
    id: "28",
    title: "Paralegal",
    company: "LawFirst",
    location: "Miami, FL",
    type: "Full-time",
    salary: "$60k - $80k",
    description: "Support legal team with research and documentation...",
    requirements: ["Paralegal cert", "Legal research", "Organization"],
    responsibilities: ["Document prep", "Legal research", "Case management"],
    postedDate: "2024-01-14",
    logo: "LF",
    category: "Legal",
    experienceLevel: "Entry",
    skills: [
      "Legal research",
      "Document management",
      "Westlaw",
      "Microsoft Office",
    ],
    benefits: ["Certification support", "Flexible hours", "Health insurance"],
    applyCount: 24,
    remote: true,
  },

  // Healthcare
  {
    id: "29",
    title: "Healthcare Administrator",
    company: "HealthFirst",
    location: "Boston, MA",
    type: "Full-time",
    salary: "$85k - $115k",
    description: "Manage healthcare facility operations...",
    requirements: ["Healthcare admin", "Regulations", "Leadership"],
    responsibilities: ["Staff management", "Compliance", "Patient relations"],
    postedDate: "2024-01-07",
    logo: "HF",
    category: "Healthcare",
    experienceLevel: "Mid",
    skills: ["HIPAA", "EMR systems", "Budgeting", "Staff management"],
    benefits: ["Medical benefits", "Retirement plan", "Tuition reimbursement"],
    applyCount: 29,
    remote: false,
  },
  {
    id: "30",
    title: "Medical Writer",
    company: "MedComms",
    location: "Remote",
    type: "Remote",
    salary: "$70k - $95k",
    description: "Create medical and scientific content...",
    requirements: ["Science background", "Writing skills", "Research"],
    responsibilities: [
      "Regulatory documents",
      "Journal articles",
      "Presentations",
    ],
    postedDate: "2024-01-12",
    logo: "MC",
    category: "Healthcare",
    experienceLevel: "Entry",
    skills: ["Scientific writing", "Research", "PubMed", "AMA style"],
    benefits: ["Flexible schedule", "Conference access", "Home office"],
    applyCount: 18,
    remote: true,
  },

  // Additional Tech Jobs
  {
    id: "31",
    title: "Security Engineer",
    company: "CyberSecure",
    location: "Washington, DC",
    type: "Full-time",
    salary: "$150k - $190k",
    description: "Protect systems and data from security threats...",
    requirements: [
      "Cybersecurity",
      "Penetration testing",
      "Security frameworks",
    ],
    responsibilities: [
      "Security audits",
      "Threat monitoring",
      "Incident response",
    ],
    postedDate: "2024-01-09",
    logo: "CS",
    category: "Security",
    experienceLevel: "Senior",
    skills: ["Penetration testing", "SIEM", "Firewalls", "ISO 27001"],
    benefits: ["Security certs", "On-call bonus", "Clearance bonus"],
    applyCount: 43,
    remote: true,
  },
  {
    id: "32",
    title: "Game Developer",
    company: "GameStudio",
    location: "Los Angeles, CA",
    type: "Full-time",
    salary: "$100k - $140k",
    description: "Create engaging games for mobile and console...",
    requirements: ["Unity/Unreal", "C#/C++", "Game design"],
    responsibilities: ["Game mechanics", "Optimization", "Bug fixing"],
    postedDate: "2024-01-11",
    logo: "GS",
    category: "Gaming",
    experienceLevel: "Mid",
    skills: ["Unity", "C#", "Game physics", "Shader programming"],
    benefits: ["Game library", "Dev kit", "Creative freedom"],
    applyCount: 67,
    remote: true,
  },
  {
    id: "33",
    title: "Blockchain Developer",
    company: "CryptoStart",
    location: "Remote",
    type: "Remote",
    salary: "$160k - $220k",
    description: "Develop smart contracts and DeFi applications...",
    requirements: ["Solidity", "Web3", "Smart contracts"],
    responsibilities: [
      "Smart contract dev",
      "Blockchain integration",
      "Security audits",
    ],
    postedDate: "2024-01-10",
    logo: "CS",
    category: "Blockchain",
    experienceLevel: "Senior",
    skills: ["Solidity", "Ethereum", "Web3.js", "Hardhat"],
    benefits: ["Crypto bonus", "Remote first", "Conference tickets"],
    applyCount: 81,
    remote: true,
  },
];
